(function(){function a(a){for(var b in a){var c=$({latitude:"#slider_lat",longitude:"#slider_lon",diameter:"#slider_diameter",coneHeight:"#slider_extrudeZ",aperture:"#slider_aperture"}[b]),d=a[b],d={min:d.min,max:d.max,value:d["default"],step:d.step,isRTL:d.isRTL};_.defaults(d,{value:(d.min+d.max)/2,step:(d.max-d.min)/c.width()});c.slider(d)}$(".slider").on("slide",function(a,b){requestUpdateUI()});$("#buy_me").click(function(a){var b=[sphere.NUM_LAT,sphere.NUM_LON];sphere.unrollAll().forEach(function(a){a.forEach(function(a){b.push(a.x.toFixed(5));
b.push(a.y.toFixed(5))})});a=b.join("\r\n");var h=renderer.domElement.toDataURL().replace(/^data:image\/(png|jpg);base64,/,"");$.post("/submit_order.php",{data:a,ss_url:stateToURL(),imageData:h},function(a,b,h){"success"!=b?alert("something went wrong: "+a):alert(a)})})}function b(a){function b(){$("#pre-assembled")[0].checked?$("#checkmark").show():$("#checkmark").hide();requestUpdateUI()}$("#pre-assembled").click(function(a){a=$("#pre-assembled")[0].checked;$("#pre-assembled")[0].checked=!a;b()});
$("#pre-assembled")[0].checked=!!a;b()}function c(){var a=$("#slider_lon").slider("value"),b=$("#slider_lat").slider("value"),c=$("#slider_diameter").slider("value"),d=$("#slider_extrudeZ").slider("value"),f=$("#slider_aperture").slider("value"),m=$("#canvas_skew")[0].skew,q=$("#canvas_profile")[0].profile,p=$("#pre-assembled")[0].checked;e(a,b,c,d,f,m,q);window.sphere&&(b=function(a){var b=null;a.traverse(function(a){a=a.geometry;void 0!==a&&(a.computeBoundingBox(),null===b?b=a.boundingBox:b.union(a.boundingBox))});
return b}(sphere),a=b.max.y-b.min.y,b=b.max.x-b.min.x,$("#dimensions_indicator").text(a.toFixed(2)+'" x '+b.toFixed(2)+'"'));a=g;p&&(a+=n);$("#cost_indicator").text("$"+a.toFixed(2));k=!1}function e(a,b,c,d,f,e,g){void 0!=sphere&&scene.remove(sphere);_.any(arguments,function(a){return void 0===a})||(sphere=new Sphere(a,b,c,d,f,e,g),scene.add(sphere))}function d(){var a=$("#container"),b=a.width(),c=a.height(),d=b/c;renderer=Detector.webgl?new THREE.WebGLRenderer({preserveDrawingBuffer:!0}):new THREE.CanvasRenderer;
renderer.setClearColorHex(0,1);camera=new THREE.PerspectiveCamera(60,d,0.1,1E4);scene=new THREE.Scene;camera.position.set(10,10,20);renderer.setSize(b,c);a.append(renderer.domElement);controls=new THREE.TrackballControls(camera,renderer.domElement);controls.rotateSpeed=1;controls.zoomSpeed=1.2;controls.panSpeed=0.8;controls.noZoom=!1;controls.noPan=!0;controls.staticMoving=!1;controls.dynamicDampingFactor=0.3;controls.keys=[65,83,68];stats=new Stats;stats.setMode(0);stats.domElement.style.position=
"relative";stats.domElement.style.left="0px";stats.domElement.style.top="0px";scene.add(camera);(function(a){var b=new THREE.DirectionalLight(5592405);b.position.set(0,-0.5,-0.5);a.add(b);b=new THREE.DirectionalLight(6710886);b.position.set(0,0.5,-0.5);a.add(b);b=new THREE.DirectionalLight(5592405);b.position.set(-0.8,-0.2,0.1);a.add(b);b=new THREE.DirectionalLight(8947848);b.position.set(0.1,0.2,0.9);a.add(b);a.add(new THREE.AmbientLight(5592405))})(scene);a=function(){function a(b){b=new THREE.MeshPhongMaterial(b);
var c=new THREE.CylinderGeometry(0.3,0.3,3,20,1,!0);c.applyMatrix((new THREE.Matrix4).makeTranslation(0,1.5,0));var d=new THREE.CylinderGeometry(0,0.7,1.5,20,1,!1);d.applyMatrix((new THREE.Matrix4).makeTranslation(0,3.75,0));THREE.GeometryUtils.merge(c,d);return new THREE.Mesh(c,b)}var b=new THREE.Object3D,c=a({color:10092604,ambient:16711779});b.add(c);var c={color:12303291,ambient:8421504},d=a(c);d.rotation.set(0,0,-Math.PI/2);b.add(d);c=a(c);c.rotation.set(Math.PI/2,0,0);b.add(c);c=new THREE.Mesh(new THREE.SphereGeometry(0.6),
new THREE.MeshLambertMaterial({color:16777215,emissive:8421504}));b.add(c);b.scale.set(0.01,0.01,0.01);return b}();window.axis=a;scene.add(a);window.sphere=void 0;requestUpdateUI()}function f(){stats.begin();requestAnimationFrame(f);controls.update();camera.updateMatrix();camera.updateMatrixWorld(!0);k&&c();var a=new THREE.Vector3(THREE.Math.mapLinear(55,0,renderer.domElement.width,-1,1),THREE.Math.mapLinear(55,0,renderer.domElement.height,1,-1),0.5);(new THREE.Projector).unprojectVector(a,camera);
a=a.sub(camera.position).setLength(0.5);axis.position.copy(camera.position);axis.position.add(a);renderer.render(scene,camera);stats.end()}var g,n,k=!1;window.requestUpdateUI=function(){k=!0};window.paramStateToJSON=function(){return{longitudes:$("#slider_lon").slider("value"),latitudes:$("#slider_lat").slider("value"),diameter:$("#slider_diameter").slider("value"),extrudeZ:$("#slider_extrudeZ").slider("value"),aperture:$("#slider_aperture").slider("value"),skew:$("#canvas_skew")[0].skew,profile:$("#canvas_profile")[0].profile}};
THREE.SplineCurve.prototype.toJSON=function(){return this.points};window.paramStateToFlatJSON=function(){var a=window.paramStateToJSON();return JSON.parse(JSON.stringify(a))};window.paramStateFromFlatJSON=function(a){var b={longitudes:$("#slider_lon"),latitudes:$("#slider_lat"),diameter:$("#slider_diameter"),extrudeZ:$("#slider_extrudeZ"),aperture:$("#slider_aperture"),skew:function(a){Processing.getInstanceById("canvas_skew").setSkew(a.x,a.y)},profile:function(a){if(!Processing.getInstanceById("canvas_profile").setProfileModel)debugger;
Processing.getInstanceById("canvas_profile").setProfileModel(a)}},c;for(c in b){if(!(c in a))throw{name:"KeyError",message:c+" not specified!"};if("function"==$.type(b[c]))b[c](a[c]);else b[c].slider("value",a[c])}};window.stateToURL=function(){var a=window.paramStateToFlatJSON();return location.origin+location.pathname+"?"+$.param(a)};window.tryLoadStateFromURL=function(){var a=$.url().param();json=JSON.parse(JSON.stringify(a),function(a,b){return isNaN(parseFloat(b))?b:parseFloat(b)});window.paramStateFromFlatJSON(json)};
(function(){function c(){if(!0===e&&!0===k&&!0===!!l){var h=jsyaml.load(l);b(h.preassemble);g=h.BASE_PRICE||149.99;n=h.PREASSEMBLED_COST||50;a(h);if(!_.isEmpty($.url().param()))try{tryLoadStateFromURL()}catch(m){throw m;}d();f()}}var e=!1,k=!1,l=!1;$(window).on("skew_control_loaded",function(){e=!0;c()});$(window).on("profile_control_loaded",function(){k=!0;c()});$.get("parameters.txt",function(a){l=a;c()})})()})();function Sphere(a,b,c,e,d,f,g){THREE.Object3D.call(this);this.OPENING_DIAMETER=5;this.NUM_LON=a;this.NUM_LAT=b;this.diameter=c;this.extrudeZ=e;this.aperture=d;this.skew=f;this.profile=g;this.latStart=-Math.acos(this.OPENING_DIAMETER/this.diameter);this.latEnd=-this.latStart;this.trapezoids=[];for(a=0;a<this.NUM_LON;a+=1)for(b=0;b<this.NUM_LAT;b+=1)c=new TrapezoidGeometry(this,a,b),e=new THREE.MeshLambertMaterial({color:16777215,side:THREE.DoubleSide}),e=new THREE.Mesh(c,e),this.add(e),void 0===this.trapezoids[b]&&
(this.trapezoids[b]=c)}Sphere.prototype=Object.create(THREE.Object3D.prototype);Sphere.prototype.unrollAll=function(){return this.trapezoids.map(function(a){return a.unroll()})};
Sphere.prototype.profileScalar=function(a){a=this.toLatAngle(a);a=THREE.Math.mapLinear(Math.sin(a),Math.sin(this.latStart),Math.sin(this.latEnd),0,1);return function(a){for(var c=function(a){return this.profile.getPointAt(a)}.bind(this),e=0,d=1,f=(d+e)/2,g=c(f).y;1E-4<Math.abs(a-g);)a>g?e=f:d=f,f=(d+e)/2,g=c(f).y;return c(f).x}.call(this,a)};Sphere.prototype.toLonAngle=function(a){return THREE.Math.mapLinear(a,0,this.NUM_LON,0,2*Math.PI)};
Sphere.prototype.toLatAngle=function(a){return THREE.Math.mapLinear(a,0,this.NUM_LAT,this.latStart,this.latEnd)};function fromSpherical(a,b,c){return new THREE.Vector3(a*Math.cos(b)*Math.cos(c),a*Math.sin(c),a*Math.sin(b)*Math.cos(c))}function lerp(a,b,c){return a.set(THREE.Math.mapLinear(c,0,1,a.x,b.x),THREE.Math.mapLinear(c,0,1,a.y,b.y),THREE.Math.mapLinear(c,0,1,a.z,b.z))}function projectScalar(a,b){return a.dot(b)/b.length()}function to3D(a){return new THREE.Vector3(a.x,a.y,0)}function angleFrom(a,b){return Math.atan2(a.x*b.y-a.y*b.x,a.x*b.x+a.y*b.y)}
function TrapezoidGeometry(a,b,c){THREE.Geometry.call(this);this.sphere=a;this.lonIndex=b;this.latIndex=c;var e=a.diameter,d=this.pointsBase=[];d.push(fromSpherical(e/2,a.toLonAngle(b),a.toLatAngle(c)));d.push(fromSpherical(e/2,a.toLonAngle(b+1),a.toLatAngle(c)));d.push(fromSpherical(e/2,a.toLonAngle(b+1),a.toLatAngle(c+1)));d.push(fromSpherical(e/2,a.toLonAngle(b),a.toLatAngle(c+1)));b=this.pointsTop=_.map(d,function(a){return a.clone()});this.origin=d[0].clone();this.xAxis=(new THREE.Vector3).subVectors(d[1],
this.origin);this.yAxis=(new THREE.Vector3).subVectors(d[3],this.origin);this.normal=(new THREE.Vector3).crossVectors(this.xAxis,this.yAxis).negate();var f=a.diameter*a.extrudeZ*a.profileScalar(c+0.5);_.each(b,function(a){a.add(this.normal.clone().setLength(f))}.bind(this));var g=b[0].clone().add(this.xAxis.clone().multiplyScalar(0.5)).add(this.yAxis.clone().multiplyScalar(0.5));_.each(b,function(b){lerp(b,g,a.aperture)});_.each(b,function(b){b.add(this.xAxis.clone().multiplyScalar(-a.skew.x)).add(this.yAxis.clone().multiplyScalar(a.skew.y))}.bind(this));
this.vertices=this.vertices.concat(d);this.vertices=this.vertices.concat(b);for(c=0;4>c;c+=1)d=new THREE.Face4(c,c+4,(c+1)%4+4,(c+1)%4),d.normal=this.vertices[d.b].clone().sub(this.vertices[d.a]).cross(this.vertices[d.d].clone().sub(this.vertices[d.a])).normalize(),this.faces.push(d);this.computeCentroids()}TrapezoidGeometry.prototype=Object.create(THREE.Geometry.prototype);
TrapezoidGeometry.prototype.faceTo2D=function(a){var b=this.vertices[a.a],c=this.vertices[a.b],e=this.vertices[a.d].clone().sub(b).normalize(),d=e.clone().cross(c.clone().sub(b)).normalize().clone().cross(e);return[a.a,a.b,a.c,a.d].map(function(a){return this.vertices[a]}.bind(this)).map(function(a){var c=a.clone().sub(b);a=projectScalar(c,e);c=projectScalar(c,d);return new THREE.Vector2(a,c)})};
TrapezoidGeometry.prototype.faceToTrapezoid=function(a,b){var c=b[2].clone().sub(b[3]),e=a[1].clone().sub(a[0]),d=to3D(b[3]),f=(new THREE.Matrix4).makeRotationZ(angleFrom(e,c));return a.map(function(a){a=to3D(a);a.applyMatrix4(f);a.add(d);return new THREE.Vector2(a.x,a.y)})};
TrapezoidGeometry.prototype.unroll=function(){var a=[this.faces[3],this.faces[0],this.faces[1],this.faces[2]].map(this.faceTo2D.bind(this)),b=a[0],c=this.faceToTrapezoid(a[1],b),e=this.faceToTrapezoid(a[2],c),a=this.faceToTrapezoid(a[3],e),d=[b[0],b[1],c[0],c[1],e[0],e[1],a[0],a[1],a[3],a[2]];return function(){var a=d.map(function(a){return new THREE.Vector2(a.x,-a.y)}),b=angleFrom(a[9].clone().sub(a[1]),new THREE.Vector2(1,0)),c=(new THREE.Matrix4).makeRotationZ(b),a=a.map(function(a){a=to3D(a).applyMatrix4(c);
return new THREE.Vector2(a.x,a.y)}),e=new THREE.Vector2(-a[0].x,-a[1].y);return a.map(function(a){return new THREE.Vector2(a.x+e.x,a.y+e.y)})}()};THREE.Vector2.prototype.toString=function(){return""+this.x.toFixed(5)+","+this.y.toFixed(5)};function ppPoints(a){return a.map(function(a){return a.toString()}).join("\n")}function ppPointsArr(a){return a.map(ppPoints).join("\n\n")}function len01(a){return a[0].clone().sub(a[1]).length()}function len23(a){return a[2].clone().sub(a[3]).length()};
